name: Validate Question
on:
  workflow_dispatch:
  workflow_call:
env:
  HACKERRANK_EMAIL: ${{ secrets.HACKERRANK_EMAIL }}
  HACKERRANK_PASSWORD: ${{ secrets.HACKERRANK_PASSWORD }}
  HACKERRANK_STACKS: ${{ vars.HACKERRANK_STACKS }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout workflows repo
        uses: actions/checkout@v3
        with:
          repository: Automation-University/workflows
          path: workflows
      - name: run script
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9'
      - run: zip -r project.zip ./main/ -x '*.git*'
      - run: pip install -r ./workflows/.github/scripts/requirements.txt
      - run: python -u ./workflows/.github/scripts/validate.py ${{ github.event.repository.name }}